# Generated by Django 5.1.7 on 2025-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_sizes_alter_sizeoption_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeoption',
            name='code',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('STD', 'Standard')], max_length=3),
        ),
    ]
