# Generated by Django 5.1.7 on 2025-04-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeoption',
            name='product',
        ),
    ]
