# Generated by Django 5.1.7 on 2025-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_shipping_cost_order_shipping_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='eir_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line1',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
